Add typehints and modules to Rust code
xivlogs/nari pull request #101
Opened 2022-07-25 04:13 UTC by ayyaruq

**Purpose**
Initially I wanted to just add type hints. Scope creep happened and now it's also renaming the dir as well as setting up fake python modules. `rustfmt` was also run so basically the diff is huge, recommend looking at specific commits.

For the module layout, I chose to do nested modules inline, but there's no reason they couldn't be registered distinctly and then connected later. The hack comment is to force it to present as real packages to simplify imports on the python side. Could use folders in rust too but I see little benefit to it at this point.

**New Features**
- python can now see type hints for rust functions
- python can import with submodules (`from nari_act_ext.utils import get_time_milliseconds`), allowing python to stub the same structure for fallback

**Before/After**
Before: `act/ext/`
After: `act/rust/`

**Additional Context**
Might help to look at this as individual commits or sets of, since the diff is full-file due to dir rename and `rustfmt`.

2022-07-25 10:44 UTC, wolfcomp commented on act/rust/lines_to_params.rs
> +#[pyo3(text_signature = "(params: list[str]) -> list[any]")]
This should have a return type of `tuple[tuple[int,str],list[int],list[float],tuple[int,str],list[int],list[float],list[tuple[int,int,int,int,int,int,int]],int]`

2022-07-25 10:44 UTC, wolfcomp commented on act/rust/lines_to_params.rs
> +#[pyo3(text_signature = "(params: list[str]) -> list[int]")]
This should be `tuple[int,int,int,int,int,int,int]`

2022-07-25 10:45 UTC, wolfcomp commented on act/rust/lines_to_params.rs
> +#[pyo3(text_signature = "(params: list[str]) -> list[any]")]
This should be return type `tuple[tuple[int,str],str,list[int],list[float],list[tuple[int,int,float,int]]]`

2022-07-25 10:46 UTC, wolfcomp commented on act/rust/parser.rs
> +#[pyo3(text_signature = "(params: list[str]) -> list[int]")]
This should be return type `tuple[int,int,int,int]`

2022-07-26 03:52 UTC, nonowazu requested changes

2022-07-26 03:52 UTC, nonowazu commented on act/rust/lib.rs
> +    // HACK: abuse python imports to make `from rustext.utils import validate_checksum` work
could we add some more docs for this, just in case there's a better way that comes out later.

2022-07-26 03:56 UTC, nonowazu approved these changes

2022-07-26 03:57 UTC, merged