first implementation of gauge parser
xivlogs/nari pull request #18
Opened 2021-03-02 02:04 UTC by joooooooooe-star

**Purpose**
Creating the parser for gauge events

**Additional Context**
I am pretty sure this is not what is intended but I can probably fix it so it will match whatever it was for

2021-03-02 04:17 UTC, lunarrize requested changes
Good first pass IMO, but we'll prob need to iterate on this a few times

2021-03-02 04:17 UTC, lunarrize commented on nari/types/gauge.py
> +    def convert_line_to_gauge(params: List[str]) -> tuple:
act line parsing should go under `nari/io/reader/actlogutils` as a helper function

2021-03-02 04:17 UTC, lunarrize commented on nari/types/gauge.py
> +        Job.RDM: "<BBBxxxxx",
this is a style pref thing, but you should prob use `!` instead of `<` since the [python docs](https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment) say this is network and the rest of the codebase uses `!` too for struct unpacks

2021-03-02 04:17 UTC, lunarrize commented on nari/types/gauge.py
> +        Job.RDM: "<BBBxxxxx",
also, these probably need docstrings for pydoc. Also, prob best to move these into something like `nari/types/gauge` since these are definitions and this bloats the object imo

2021-03-02 04:17 UTC, lunarrize commented on nari/types/gauge.py
>  """Stuff for gauge of actors"""
this is hard.. some of this needs to be under `nari/types/event/gauge.py` (as a new file), and some of this needs to be under `nari/types/gauge`

2021-03-02 04:17 UTC, lunarrize commented on nari/types/gauge.py
> +    def convert_bytes_to_data(gauge_bytes: tuple[int]) -> Dict[str, Any]:
prob best to keep staticmethod out of these, since none of the other events use them.. maybe make it a helper function instead somewhere

2021-03-04 07:02 UTC, joooooooooe-star commented on nari/types/gauge.py
> +    def convert_line_to_gauge(params: List[str]) -> tuple:
i moved it and hopefully i did it properly

2021-03-04 07:03 UTC, joooooooooe-star commented on nari/types/gauge.py
> +        Job.RDM: "<BBBxxxxx",
removed job stuff since it seems out of scope of nari

2021-03-04 07:03 UTC, joooooooooe-star commented on nari/types/gauge.py
>  """Stuff for gauge of actors"""
removed job stuff since it seems out of scope of nari

2021-03-04 07:03 UTC, joooooooooe-star commented on nari/types/gauge.py
> +    def convert_bytes_to_data(gauge_bytes: tuple[int]) -> Dict[str, Any]:
converted to helper function in actlogutil

2021-03-04 17:43 UTC, lunarrize requested changes
Much better this time, thank you for working with the feedback. I'll reach out over discord to discuss stuff with tests so it can just become part of the project

2021-03-04 17:43 UTC, lunarrize commented on nari/io/reader/actlogutils/__init__.py
> +    ActEventType.gauge: gauge_from_logline(),
Need to remove the `()`, since we're handing it the function as a variable and not calling the function

2021-03-04 17:43 UTC, lunarrize commented on nari/io/reader/actlogutils/gauge.py
> +from nari.types.event.gauge import Gauge
stylistic request - have a blank line between standard modules (like datetime and typing) and local nari imports

2021-03-04 17:43 UTC, lunarrize commented on nari/io/reader/actlogutils/gauge.py
> +    """Parses gauge event out from act log line"""
The other functions in this module have a breakout of what all the act args are, so someone else coming along can know what they're for. Can you do the same here?

2021-03-04 17:43 UTC, lunarrize commented on nari/io/reader/actlogutils/tests/test_gauge.py
> +                      "|083c7ec0220b2c890503f47c3f265078"
don't worry about str length unless it's really bad. It's okay to combine these

2021-03-04 17:43 UTC, lunarrize commented on nari/types/event/gauge.py
> +    def __eq__(self, other):
This is prob overkill. Is there a reason we need this?

2021-03-05 05:12 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/__init__.py
> +    ActEventType.gauge: gauge_from_logline(),
good catch, i screwed that one up lol

2021-03-05 05:12 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/gauge.py
> +from nari.types.event.gauge import Gauge
done

2021-03-05 05:12 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/gauge.py
> +    """Parses gauge event out from act log line"""
done

2021-03-05 05:13 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/tests/test_gauge.py
> +                      "|083c7ec0220b2c890503f47c3f265078"
done but also removing tests from PR until we resolve how to deal with them

2021-03-05 05:13 UTC, joooooooooe-star commented on nari/types/event/gauge.py
> +    def __eq__(self, other):
yeh i only used it for the test so i'll take it while we figure out what to do

2021-03-05 06:12 UTC, ayyaruq reviewed
Shaping up nicely, regarding tests, I see we're using `unittest` but should we maybe decide on a library or framework to run all our tests instead of arbitrary tests in a given folder?

2021-03-05 06:12 UTC, ayyaruq commented on nari/io/reader/actlogutils/gauge.py
> +    #       destructuring later. I have no idea what's in 4 and could not find documentation for it.
I'd probably expand on this being a union, something like "Gauge data is a struct union with fields depending on job. ACT represents this as an array of 4x 32-bit unsigned ints, so they're left as bytes for destructuring later." Prob don't need to mention the 4th param being unknown, since it's likely padding to accomodate the largest option in the union.

2021-03-05 06:12 UTC, ayyaruq commented on nari/io/reader/actlogutils/gauge.py
> +    gauge_data = tuple((string_to_bytes(param) for param in params[1:5]))
Given the array isn't actually this long, it's probably cleaner to write this as `params[1:]` so it auto adjusts to the real length.

2021-03-05 06:12 UTC, ayyaruq commented on nari/io/reader/actlogutils/gauge.py
> +    return bytes_data
Is there no utility for this? Seems relatively simple, so a bit odd to run here. Could be fine, I'm far from a Python expert, it just sticks out a bit.

2021-03-05 07:11 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/gauge.py
> +    gauge_data = tuple((string_to_bytes(param) for param in params[1:5]))
i think the list is actually longer

for test string:
"31|2021-02-04T21:51:04.3820000+09:00|1029BDAA|300001C|00|800|426E3855|083c7ec0220b2c890503f47c3f265078"

and params[0] is "1029BDAA", 
params[1:] picks up the last "083c..." and i have no idea what that is

i think other places in the code used something like params[1:-1] but i think this is cleaner, i can change that if it fits the style better

2021-03-05 07:41 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/gauge.py
> +    return bytes_data
i used that because i ~stole~ borrowed it from somewhere in the code base. i'm not sure if there's anything better, i did find these methods which seems to make more sense even though it adds a line of code

```python
param_expanded = param.zfill(8)
bytes_arr = bytearray.fromhex(param_expanded)
bytes_arr.reverse()  # switch the endianness

return bytes(bytes_arr)
```

or maybe i should just convert all numbers into a single bytes object instead of a tuple with four four-byte bytes objects?

2021-03-06 02:20 UTC, ayyaruq commented on nari/io/reader/actlogutils/gauge.py
> +    gauge_data = tuple((string_to_bytes(param) for param in params[1:5]))
That's the line checksum hash, I thought we prune it first but maybe not.. Could be some kind of preprocessing we should be doing tho since it doesn't make much sense for the event parsers to care about.

2021-03-06 02:21 UTC, ayyaruq commented on nari/io/reader/actlogutils/gauge.py
> +    return bytes_data
Not sure about the best representation of the bytes, but `string_to_bytes` seems like a relatively common transform and should prob be a utility function if it's not already. @lunarrize thoughts?

2021-03-08 07:38 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/gauge.py
> +    gauge_data = tuple((string_to_bytes(param) for param in params[1:5]))
you're right. it is pruned (that's where that [:-1] came from, from actlogs.py where the params passed into event are [2:-1]).

personally i would prefer it being [1:5] because it becomes a fixed and predictable length but i will change it as requested

2021-03-08 07:43 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/gauge.py
> +    #       destructuring later. I have no idea what's in 4 and could not find documentation for it.
changed to something similar to what you said, i think i made changes for brevity but i'm not sure if my interpretation was any clearer lol

2021-03-08 07:47 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/gauge.py
> +    return bytes_data
there is this in util/byte.py, but i think it doesn't make sense to use int types for passing around bytes? i dunno

```python
def hexstr_to_byte(string: str, pad: bool = True) -> int:
    """Converts a hexstring to a byte; items less than 4 characters 'wide' are padded"""
    if pad:
        return int(string.rjust(4, '0'), 16)
    return int(string, 16)
 ```

2021-03-08 14:29 UTC, lunarrize commented on nari/io/reader/actlogutils/gauge.py
> +    return bytes_data
dunno what the other dev wanted, but we might want to add that function to `util/byte.py`, and prob consider changing `hexstr_to_byte` to `hexstr_to_int`. Maybe even `hexstr_to_bytes`?

2021-03-08 18:20 UTC, lunarrize requested changes
Looks good, just remove the test files until we can decide what we want to do with testing 👍

2021-03-09 01:58 UTC, ayyaruq commented on nari/io/reader/actlogutils/gauge.py
> +    return bytes_data
I think that's a reasonable solution. Add the function to util and make sure the name is appropriate.

2021-03-09 11:55 UTC, ayyaruq commented
Looks great now, cheers! We can probably tidy up some of the docstrings and address those TODOs in a later PR, especially keen on having exceptions being used. Nice work!

2021-03-09 14:19 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/gauge.py
> +    gauge_data = tuple((string_to_bytes(param) for param in params[1:5]))
maybe the right play is to pop actor_id from the list and then consume the rest?

actually thinking about it it does seem weird that actor_id is int but params are bytes...

2021-03-10 11:44 UTC, ayyaruq commented on nari/io/reader/actlogutils/gauge.py
> +    gauge_data = tuple((string_to_bytes(param) for param in params[1:5]))
They're all technically bytes, we just don't parse the bytes into ints at the top level since the specific integer sizes are dependent on which job's gauge it is since it's a struct union. Actor ID is treated as an int because it's a known size at all times. Shifting it off the array isn't necessarily a bad idea tho, but I'm not sure of the performance impact or how that'll effect memory for Python.

2021-03-12 01:44 UTC, lunarrize approved these changes

2021-03-12 01:44 UTC, merged