initial commit for playerstats module
xivlogs/nari pull request #22
Opened 2021-04-11 16:05 UTC by joooooooooe-star

my first try at playerstats module though i forgot where i got the reference

2021-04-13 01:09 UTC, lunarrize requested changes
small change but otherwise good

2021-04-13 01:09 UTC, lunarrize commented on nari/io/reader/actlogutils/playerstats.py
> +        del player_stats["delete"]
You need to remove this since this will always raise an exception now.

2021-04-14 11:09 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/playerstats.py
> +        del player_stats["delete"]
this is old and many other things were fixed

2021-04-25 02:34 UTC, merged

2021-04-25 02:34 UTC, lunarrize reviewed
👍