breaks stats into attrs and fixes line parse
xivlogs/nari pull request #32
Opened 2021-05-18 15:43 UTC by joooooooooe-star

**Purpose**
1: Player event parse was not correct
2: Breaks stats into attributes

**New Features**
None

**Bug Fixes**
Mentioned by Luna in the Discord

**Before/After**
Waiting for tests to make sure it works

**Additional Context**
I am 100% sure this is ugly is sin and I'm hoping I'm on the right track and someone can provide some sort of feedback to make it look prettier

2021-05-18 18:06 UTC, lunarrize requested changes

2021-05-18 18:06 UTC, lunarrize commented on nari/io/reader/actlogutils/playerstats.py
> +    stats: Dict[Stats, int] = {param_to_stat[i]: param for i, param in enumerate(param_ints)}
why not do this

```python
stat_order: List[Stats] = [Stats.STR, Stats.DEX, Stats.VIT, ...]
stats: Dict[Stats, int] = {stat: v for stat,v in zip(stat_order, param_ints)}
```

2021-05-20 14:25 UTC, joooooooooe-star commented on nari/io/reader/actlogutils/playerstats.py
> +    stats: Dict[Stats, int] = {param_to_stat[i]: param for i, param in enumerate(param_ints)}
fixed

2021-05-20 16:03 UTC, lunarrize requested changes
looks good just add docs back

2021-05-20 16:03 UTC, lunarrize commented on nari/io/reader/actlogutils/playerstats.py
> -    16: TENACITY
why were these lines removed? they document the params

2021-05-24 01:33 UTC, lunarrize approved these changes
thanks

2021-05-24 01:33 UTC, merged