Add partylist event
xivlogs/nari pull request #39
Opened 2021-08-04 21:50 UTC by nonowazu

**Purpose**
You know what I'm here for. I'm here to make friends and implement PartyList.
...and I'm all out of Friends.

**New Features**
Adds PartyList event and helping parser for act

**Bug Fixes**
N/A

**Before/After**
Before: No PartyList event
After: PartyList event

**Additional Context**
I listened to the Smash Mouth cover of *Why Can't We Be Friends* while I wrote this. Now I have no friends.

2021-08-05 12:45 UTC, lunarrize requested changes
needs some changes but otherwise fine

2021-08-05 12:45 UTC, lunarrize commented on nari/io/reader/actlogutils/party.py
> +from datetime import datetime, time
You're not using `time`

2021-08-05 12:45 UTC, lunarrize commented on nari/io/reader/actlogutils/party.py
> +    else:
You don't need this else the `if` already returns

2021-08-05 12:45 UTC, lunarrize commented on nari/io/reader/actlogutils/party.py
> +        # TODO: parse other_ids
Go ahead and implement this

2021-08-05 12:45 UTC, lunarrize commented on nari/types/event/party.py
> +    ):
while this is okay I think other modules visually align this with the opening `(`

2021-08-11 02:49 UTC, nonowazu commented
Changes in – sorry for the delay!

2021-08-11 13:48 UTC, lunarrize requested changes

2021-08-11 13:48 UTC, lunarrize commented on nari/io/reader/actlogutils/party.py
> +    other_ids = [int(i) for i in params[amount+1:]]
both of these should be `int(i, 16)`

2021-08-11 14:25 UTC, merged