Add networkeffectresult event(s) and actlog parsing
xivlogs/nari pull request #40
Opened 2022-01-07 15:37 UTC by nonowazu

**Purpose**
This is a first pass at adding networkeffectresult events and parsing to the actlogreader

**New Features**
The event and parsing

**Bug Fixes**
Probably lots of them which are unfixd

**Before/After**
New event if you were to do the following:

```python
for event in reader: # reader is of type ActLogReader
    print(event)
```

**Additional Context**
I'm sad.

2022-01-10 04:17 UTC, ayyaruq approved these changes

2022-01-14 02:35 UTC, lunarrize requested changes

2022-01-14 02:35 UTC, lunarrize commented on nari/io/reader/actlogutils/effectresult.py
> +    sequence_id = int(params[2], 16)
if seq id is from actions we need to add it to other event types for confirmation

2022-01-14 02:35 UTC, lunarrize commented on nari/io/reader/actlogutils/effectresult.py
> +        effect_duration = unpack('<f', int(params[i+2].zfill(8), 16).to_bytes(4, 'little'))
are `i+2` indexes guaranteed to exist?

2022-01-16 03:44 UTC, nonowazu commented on nari/io/reader/actlogutils/effectresult.py
> +    sequence_id = int(params[2], 16)
I made an issue for it: #41

2022-01-16 03:45 UTC, nonowazu commented on nari/io/reader/actlogutils/effectresult.py
> +        effect_duration = unpack('<f', int(params[i+2].zfill(8), 16).to_bytes(4, 'little'))
Unless the generated act log is broken, in which case that's a bigger issue I guess?

2022-01-16 15:47 UTC, lunarrize approved these changes

2022-01-16 15:49 UTC, merged