Add ACT line checksum validation
xivlogs/nari pull request #47
Opened 2022-01-29 17:00 UTC by nonowazu

This does not improve pylint, as in the process of implementing this, I
discovered that several ACT line IDs were missing from the `ID_MAPPINGS`
dict.

Outside of that, this does a few things:

* Add checksum validation helper function to `nari.io.reader.actlogutils`
* Add a (passing) validation test to `test/actlog/test_act_utils.py`
* Fix a bug in effectresult parsing (ironically mypy was happy with it,
  but it's incorrect python)

**Purpose**
Add ACT line checksum validation, and fixed a small item that keeps the library from working.

**New Features**
ACT line checksum validation, complete with a unit test.

**Bug Fixes**

There was a bug in effectresult parsing which caused an issue:

```python
effect_duration, _ = unpack('<f', int(params[i+2].zfill(8), 16).to_bytes(4, 'little'))
```

You can't unpack a single value as if it were a tuple; adding a `*_` implies a "zero or more" unpacking, which avoids this *and* keeps mypy happy.

2022-01-29 19:56 UTC, lunarrize requested changes

2022-01-29 19:56 UTC, lunarrize commented on nari/io/reader/actlogutils/effectresult.py
> +        effect_duration, *_ = unpack('<f', int(params[i+2].zfill(8), 16).to_bytes(4, 'little'))
Why is this required? unpack should only return one value with that str

2022-01-29 19:56 UTC, lunarrize commented on test/actlog/test_act_utils.py
> +    unittest.main()
lint isn't applied here but add a newline at the end

2022-01-29 23:30 UTC, nonowazu commented on nari/io/reader/actlogutils/effectresult.py
> +        effect_duration, *_ = unpack('<f', int(params[i+2].zfill(8), 16).to_bytes(4, 'little'))
`unpack` returns a tuple it seems:

```python
>>> from struct import unpack
>>> some_value = 0xffff
>>> unpack('<f', some_value.to_bytes(4, 'little'))
(9.183409485952689e-41,)
```

By using `*_`, we can unpack and ignore that there's no other values.

2022-01-31 04:07 UTC, lunarrize approved these changes

2022-01-31 04:07 UTC, merged