Cleanup event type docstrings
xivlogs/nari pull request #75
Opened 2022-04-07 04:51 UTC by ayyaruq

Also some minor code style changes for consistency. Not sure if this is actually our preferred style, but it's consistent and I went with the more common case as a basis.

Other changes, the cast events were changed to use prefixes like everything else, and the cast type param was renamed to the cause since that's what it's used for and is more consistent with other community tools such as xivanalysis.

2022-04-07 04:59 UTC, nonowazu requested changes
Mostly questions and perhaps one change.

2022-04-07 04:59 UTC, nonowazu commented on nari/types/event/actorspawn.py
> +class ActorSpawn(Event): # pylint: disable=too-few-public-methods,duplicate-code
Where is this considered duplicate code?

2022-04-07 04:59 UTC, nonowazu commented on nari/types/event/casts.py
> +class CastStopCause(IntEnum):
Why rename this from `Type` to `Cause`? I feel like `Type` fits the enum specifier a bit better

2022-04-07 04:59 UTC, nonowazu commented on nari/types/event/updatehpmp.py
> +# pylint: disable=duplicate-code
Ditto on "why is this now duplicate code"? Is it because of some recent pylint change?

2022-04-07 06:17 UTC, ayyaruq commented on nari/types/event/actorspawn.py
> +class ActorSpawn(Event): # pylint: disable=too-few-public-methods,duplicate-code
UpdateHpMp, idk why tho.

2022-04-07 06:17 UTC, ayyaruq commented on nari/types/event/casts.py
> +class CastStopCause(IntEnum):
The values are causes, type is a spicy word to use since it's so vague while also a keyword in many languages. Category could work if you focus more on the classing of it than the usage I guess.

2022-04-07 06:18 UTC, ayyaruq commented on nari/types/event/updatehpmp.py
> +# pylint: disable=duplicate-code
Same as the previous one. Disabled in both mostly because idk how pylint orders them so yolo. There was no issue with these 2 lines until this PR, so it's something changed here.

2022-04-08 03:28 UTC, nonowazu commented on nari/types/event/casts.py
> +class CastStopCause(IntEnum):
I mean, `type` is a built-in function, but I think `CastStopType` is still okay. I would even think `CastStopReason` would be better than `Cause` in this case.

2022-04-08 03:31 UTC, nonowazu commented on nari/types/event/updatehpmp.py
> +# pylint: disable=duplicate-code
In this case, is it worth revisiting the parser for this event in the [actlogutils](https://github.com/xivlogs/nari/blob/e9965136c7f730b21868bed890452b3eba44447c/nari/io/reader/actlogutils/updatehp.py) and attaching the resources to the event itself?

2022-04-09 02:31 UTC, ayyaruq commented on nari/types/event/updatehpmp.py
> +# pylint: disable=duplicate-code
Not sure tbh, could always bundle the resources and have the event processor manage updating the actor tho, since realistically the parsers are to parse the params, not manage actor states.

2022-04-09 02:33 UTC, ayyaruq commented on nari/types/event/casts.py
> +class CastStopCause(IntEnum):
I still prefer `cause`, mostly because that's what xivanalysis uses for this kinda thing. Reason works tho.

2022-04-09 03:51 UTC, nonowazu requested changes
Requesting doc changes since we're doing more than just updating docs now.

2022-04-09 03:51 UTC, nonowazu commented on nari/io/reader/actlogutils/updatehp.py
> +    )
If you're going to avoid the max values, update the docs in the function to explain why we're not grabbing these values anymore.

2022-04-09 03:51 UTC, nonowazu commented on nari/types/event/casts.py
> +class CastStopCause(IntEnum):
I'm pretty insistent that we not use `Cause` in this particular case. I'm ironically more fine with `Category`, but prefer `Type`.

2022-04-09 03:59 UTC, nonowazu approved these changes

2022-04-09 04:01 UTC, nonowazu approved these changes

2022-04-09 04:13 UTC, merged