Fix validation for md5 and sha256, and some broken parsing
xivlogs/nari pull request #88
Opened 2022-07-17 14:47 UTC by ayyaruq

Need to sort out that version stuff a bit better, and the enum for the checksum prob isn't really necessary I suppose. Could use an exception for unknown algorithms too. Anyway, bug fixes.

2022-07-17 16:13 UTC, nonowazu requested changes
Some changes required, but thanks as always for the contributions.

2022-07-17 16:13 UTC, nonowazu commented on nari/types/event/version.py
> +    def after(self, ref: str) -> bool:
I'd remove this and implement the following functions signatures:

* `def __lt__(self, other) -> bool:` for less than
* `def __eq__(self, other) -> bool:` for equal

And decorate the class with `total_ordering` from functools (it'll implement `__gt__`, `__ge__`, etc for you).

Also, let's make a `nari.types.version.XIVVersion` instead of storing it locally and then pulling in a package. The file can look something like this:

```python
from dataclasses import dataclass

@dataclass(eq=True, order=True)
class XIVVersion(object):
    major: int
    minor: int
    patch: int
    build: int
```

Then, inside the Version event, (I think Wolf has the code for this somewhere), just make your `__eq__` method like this:

```python
return self.version == other.version
```

And the XIVVersion's stub'd methods will do the rest.

2022-07-17 16:13 UTC, nonowazu commented on test/actlog/test_act_utils.py
> +        self.assertEqual(validate_checksum(test_line, 1, "md5"), True)
As pointed out before, we pass a string in here, but in the ActLogReader we pass in an enum.

2022-07-18 02:32 UTC, nonowazu requested changes
Some changes required, but thanks as always for the contributions.

2022-07-18 02:32 UTC, nonowazu commented on nari/types/event/version.py
> +    build: int
Does this need to be in the event file? Would this be better in either `util` or something like `types.version`?

2022-07-18 02:32 UTC, nonowazu commented on nari/io/reader/actlog.py
> +            if validate_checksum(line.strip(), self.index, self.algo.name) is False:
I still think `self.algo.name` is gross, because you can get the same effect by changing this from an `IntEnum` to a regular `Enum` and just making the values be the string name of the key.

2022-07-18 02:34 UTC, ayyaruq commented on nari/types/event/version.py
> +    build: int
No idea, colocated for where it was used but the comparison was shifted out, so it can go anywhere.

2022-07-18 02:35 UTC, ayyaruq commented on nari/io/reader/actlog.py
> +            if validate_checksum(line.strip(), self.index, self.algo.name) is False:
I don't see this in the code anywhere.

2022-07-18 04:24 UTC, nonowazu requested changes
One tiny change. Won't impact the code any other way.

2022-07-18 04:24 UTC, nonowazu commented on nari/io/reader/actlogutils/__init__.py
> +def validate_checksum(line: str, index: int, algo: ActLogChecksumType) -> bool:
I might suggest a default, since we're expecting sha most of the time:

```python
def validate_checksum(line: str, index: int, algo: ActLogChecksumType = ActLogChecksumType.SHA256) -> bool:
```

2022-07-18 06:06 UTC, ayyaruq commented on nari/io/reader/actlogutils/__init__.py
> +def validate_checksum(line: str, index: int, algo: ActLogChecksumType) -> bool:
I was thinking that, but then we handle unknowns and all calls have the param passed anyway. It's defaulted to SHA where it's called so maybe we can shift that, not sure what's cleaner.

2022-07-18 12:47 UTC, merged