Move act-specific parsing out of nari back into nari, but in a namespace.
xivlogs/nari pull request #95
Opened 2022-07-21 14:32 UTC by nonowazu

This is exactly the same as #94 (so read that text to know how I feel about this) except namespace'd per PEP420 (except I use the pkgutil hack in nari's `__init__.py`). In the future, packages wishing to share nari's namespace *must* put their package under `nari.ext.${PACKAGE}` – the `act` directory has a show of how to do this.

2022-07-22 03:12 UTC, nonowazu commented
though the checks pass, we'll need to update ci to run tests based on what file(s) have changed (act-specific vs nari-specific)

2022-07-22 10:12 UTC, ayyaruq requested changes
Initial once over before I dig into the code. Not sure on the workflow change you made, or what's up with empty `py.typed`. Main thing of note, `act.actlogutils` is a bit redundant, perhaps rename to `act.logutils` and update dir name appropriately? That also sets a pattern for other readers.

2022-07-22 10:12 UTC, ayyaruq commented on act/.editorconfig
> +indent_size = 4
Alphabetised, and adding a markdown config as well.
```suggestion
[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

# 4 space indentation, keep trailing whitespace (MD formatting)
[*.md]
indent_size = 4
indent_style = space
trim_trailing_whitespace = false

# 4 space indentation
[*.py]
indent_size = 4
indent_style = space
```

2022-07-22 10:12 UTC, ayyaruq commented on act/.gitignore
> +# Created by https://www.gitignore.io/api/python,virtualenv,code
Can we stick to either GH template gitignores or gitignore.io? Doesn't make much diff to me which, but it'd be nicer if we were consistent across repos.

2022-07-22 10:12 UTC, ayyaruq commented on act/.gitignore
> +#Pipfile.lock
Best to make sure nobody accidentally commits a diff dependency system.
```suggestion
Pipfile
Pipfile.lock

# Poetry
PyProject.toml
poetry.lock
```

2022-07-22 10:12 UTC, ayyaruq commented on act/.gitignore
> +!.vscode/extensions.json
Let's add the IntelliJ/PyCharm stuff here too, so like `.idea` and whatnot.

2022-07-22 13:45 UTC, nonowazu commented on act/.editorconfig
> +indent_size = 4
Might want to do this as a separate PR to this; I only copied this so it would be easy to break out to its own repo when we were ready. Also, this change doesn't impact the core repo `.editorconfig`, so it might be bad to have drift between both versions.

2022-07-22 13:45 UTC, nonowazu commented on act/.gitignore
> +# Created by https://www.gitignore.io/api/python,virtualenv,code
As long as someone makes it a standard; I didn't even know that github had a template one, to be honest.

2022-07-22 13:46 UTC, nonowazu commented on act/.gitignore
> +#Pipfile.lock
Same as the `.editorconfig` comment - maybe clean up as a separate, follow-on PR.

2022-07-22 13:46 UTC, nonowazu commented on act/.gitignore
> +!.vscode/extensions.json
same as the previous `.gitignore` and `.editorconfig` comment

2022-07-23 07:32 UTC, ayyaruq commented on act/.editorconfig
> +indent_size = 4
Let's do it in this PR and then do another one to copy it into nari core as well as the API.

2022-07-23 07:33 UTC, ayyaruq commented on act/.gitignore
> +#Pipfile.lock
As above, do it here and then separate PR to update nari core and the API to use it too?

2022-07-23 07:33 UTC, ayyaruq commented on act/.gitignore
> +!.vscode/extensions.json
Same same.

2022-07-23 08:17 UTC, ayyaruq approved these changes

2022-07-23 08:19 UTC, merged